[[sources]]
name = "similar-favorites"
loader = "similar"
filters = [{ key = "playcount", operator = ">", value = 0 }]
sorts = [
    { key = "rating", weight = 1 },
    { key = "lastplay", weight = -0.5 }, # Favor less recently played tracks
]

[[sources]]
name = "similar-unplayed"
loader = "similar"
filters = [{ key = "playcount", operator = "<", value = 1 }]
sorts = [{ key = "rating", weight = 1 }]

[[sources]]
name = "random"
loader = "random"
filters = []
sorts = []

[[stations]]
name = "new-stuff"
sources = [
    { source = "similar-favorites", weight = 1 },
    { source = "similar-unplayed", weight = 2 },
]
seed = "random"
